{"name": "Проверка неуспешного логина с некорректным логином", "status": "passed", "steps": [{"name": "Выполняем логин от имени курьера", "status": "passed", "parameters": [{"name": "login", "value": "'tdcehxonob'"}, {"name": "password", "value": "'cufdnskvbp'"}], "start": 1710018472995, "stop": 1710018473435}], "start": 1710018472995, "stop": 1710018473437, "uuid": "01915daa-8ee0-4084-b6b7-f884e2d1bf54", "historyId": "7f6dcc30b066af416b23f5392d6d9ac5", "testCaseId": "7f6dcc30b066af416b23f5392d6d9ac5", "fullName": "tests.test_courier_login.TestCourierLogin#test_loggining_incorrect_login_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "pavel"}, {"name": "thread", "value": "18992-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}]}